### ISSUE TITLE
Website is slow and `ncats-webd` logs show errors

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ncats-webd#36]
# 🐛 Summary #

VS reported that the dashboard website is running slow today.  In response I restarted both `ncats-webd.service` and `ncats-webui.service`.  In the logs of the former I see a lot of stuff that looks like this:
```console
Nov 21 20:10:20 dashboard ncats-webd[19568]: Traceback (most recent call last):
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "src/gevent/_waiter.py", line 119, in gevent.__waiter.Waiter.switch
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "src/gevent/greenlet.py", line 718, in gevent._greenlet.Greenlet.run
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "src/gevent/greenlet.py", line 700, in gevent._greenlet.Greenlet._report_error
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "/usr/lib/python2.7/dist-packages/gevent/_tblib.py", line 371, in g
Nov 21 20:10:20 dashboard ncats-webd[19568]:     return f(a)
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "/usr/lib/python2.7/dist-packages/gevent/_tblib.py", line 426, in dump_traceback
Nov 21 20:10:20 dashboard ncats-webd[19568]:     return dumps(tb)
Nov 21 20:10:20 dashboard ncats-webd[19568]:   File "/usr/lib/python2.7/dist-packages/gevent/builtins.py", line 81, in __import__
Nov 21 20:10:20 dashboard ncats-webd[19568]:     if args and not issubclass(type(args[0]), _allowed_module_name_types):
Nov 21 20:10:20 dashboard ncats-webd[19568]: RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by jsf9k** [comment]
@dav3r and @mcdonnnj - Feel free to re-/unassign this issue as you see fit.  I assigned you because I wanted to make sure you saw it upon your return from the Thanksgiving holiday. :turkey:
